-- 育儿模拟器 Supabase 数据库结构
-- 使用方法：Supabase 控制台 → SQL Editor → New query → 粘贴本文件 → Run

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  room_code text unique not null,
  status text not null default 'setup',
  current_turn integer not null default 1,
  current_year integer not null default 0,
  phase text not null default 'pregnancy',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  display_name text not null,
  role text not null default 'parent',
  created_at timestamptz not null default now()
);

create table if not exists public.game_states (
  room_id uuid primary key references public.rooms(id) on delete cascade,
  setup jsonb not null default '{}'::jsonb,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_id uuid references public.players(id) on delete set null,
  author text not null default 'system',
  kind text not null default 'chat',
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  turn integer not null,
  event_type text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists rooms_room_code_idx on public.rooms(room_code);
create index if not exists players_room_id_idx on public.players(room_id);
create index if not exists messages_room_id_created_at_idx on public.messages(room_id, created_at);
create index if not exists events_room_id_created_at_idx on public.events(room_id, created_at);

-- 这个原型只让 Vercel 后端使用 service_role 访问数据库。
-- 前端不会直接连接 Supabase，所以这里不需要开放 RLS 策略。
