-- 《双星之歌：高维演化协议》（Stellar Duo）专属数据库表
-- 使用方法：Supabase 控制台 → SQL Editor → New query → 粘贴本文件 → Run

-- 1. 房间表（Stellar Rooms）
create table if not exists public.stellar_rooms (
  id uuid primary key default gen_random_uuid(),
  room_code text unique not null,
  status text not null default 'setup', -- setup: 恒星与星系设定中; active: 演化进行中; ended: 跃迁完成或毁灭
  current_turn integer not null default 1,
  current_epoch text not null default 'epoch_genesis', -- epoch_genesis, epoch_biosphere, epoch_tribal, epoch_classical, epoch_industrial, epoch_space
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. 玩家表（Stellar Players）
create table if not exists public.stellar_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.stellar_rooms(id) on delete cascade,
  display_name text not null,
  role text not null default 'spectator', -- star_alpha (主星), star_beta (伴星), spectator (观察者)
  created_at timestamptz not null default now()
);

-- 3. 行星与恒星数据状态表（Stellar Game States）
-- 存储包含双恒星设定（颜色、光谱、光谱异常判定）和行星硬核属性（温度、重力、化学基底等）的快照
create table if not exists public.stellar_game_states (
  room_id uuid primary key references public.stellar_rooms(id) on delete cascade,
  stellar_setup jsonb not null default '{
    "starAlpha": { "name": "阿尔法", "type": "G-type Yellow Dwarf", "color": "#fdb813", "mass": 1.0 },
    "starBeta": { "name": "贝塔", "type": "M-type Red Dwarf", "color": "#ff7c43", "mass": 0.4 },
    "isAnomaly": false,
    "systemNotes": "天然双星系统"
  }'::jsonb,
  planetary_state jsonb not null default '{
    "turn": 1,
    "epoch": "epoch_genesis",
    "planet": {
      "gravity": 1.0,
      "temp": 350,
      "atmoPressure": 1.0,
      "magneticField": 50,
      "biodiversity": 0,
      "habitability": 0
    },
    "civilization": {
      "techLevel": 0,
      "unity": 0,
      "reasonRatio": 50,
      "entropy": 0
    },
    "solvent": "H2O",
    "baseChemistry": "Carbon-based",
    "discoveredOrganisms": []
  }'::jsonb,
  updated_at timestamptz not null default now()
);

-- 4. 实时聊天盒与游戏播报历史表（Stellar Messages）
create table if not exists public.stellar_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.stellar_rooms(id) on delete cascade,
  player_id uuid references public.stellar_players(id) on delete set null,
  author text not null default '系统',
  kind text not null default 'chat', -- chat: 聊天键入; command: 指令; narrative: AI分段旁白叙述; anomaly_broadcast: 高维播报; system: 系统控制
  content text not null,
  created_at timestamptz not null default now()
);

-- 5. 史诗专属独立存档表（Stellar Saves）
create table if not exists public.stellar_saves (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.stellar_rooms(id) on delete cascade,
  name text not null,
  created_by text not null,
  stellar_setup jsonb not null,
  planetary_state jsonb not null,
  room_status text not null,
  current_turn integer not null,
  current_epoch text not null,
  message_max_id bigint not null default 0,
  created_at timestamptz not null default now()
);

-- 索引，提速两星数据连接定位
create index if not exists stellar_rooms_code_idx on public.stellar_rooms(room_code);
create index if not exists stellar_players_room_idx on public.stellar_players(room_id);
create index if not exists stellar_messages_room_idx on public.stellar_messages(room_id, created_at);
create index if not exists stellar_saves_room_idx on public.stellar_saves(room_id, created_at);
